### PR TITLE
Disabling execute permission on all files

### PR DESCRIPTION
**Pull request by mtlynch**
Many files in the repo have the UNIX executable permission bit set, which indicates to the OS that these are executable binaries. None of these files are executable, so they should not have the executable permission bit set.

### CODE REVIEW

**Comment by daviddarnes** [comment]
This is interesting. Has this become an issue with how you are using garth? This is the first time I've encountered this change with any Jekyll project, I'd like to understand a bit more about it before I merge it in

**Comment by mtlynch** [comment]
It doesn't really block anything, but it's just confusing for anyone working with the code. Setting the execute bit on a file means that you can run the file as an executable.

https://en.wikipedia.org/wiki/File_system_permissions#Permissions

For example, this script in my personal Jekyll project has the executable bit set intentionally because it is an executable program (specifically, a bash script):

https://github.com/mtlynch/mtlynch.io/blob/master/script/_serve_dev.sh

I can execute that program by running`./_serve_dev.sh` and the program runs.

In contrast, the files in this repo are marked as executable even though they're not really executable; they're just plaintext data. If the user attempts to run them, the shell tries to interpret them as bash scripts, but it fails because they're not executable binaries or scripts:

```bash
$ ./index.html
./index.html: line 1: ---: command not found
./index.html: line 2: layout:: command not found
./index.html: line 3: collectionpage:: command not found
./index.html: line 4: ---: command not found
```

If we remove the execute permission, the OS does not offer the user options to execute the file as a program, and if the user tries, the OS just denies the attempt:

```bash
$ chmod -x index.html # Remove the execute permission
$ ./index.html
bash: ./index.html: Permission denied
```

**Comment by daviddarnes** [comment]
Thanks for explaining! I'm interested to know how you came across this and whether it was affecting how you're using garth?

**Comment by mtlynch** [comment]
It didn't affect the way I'm using garth. I noticed the issue fixed in #22 and then while working with the code, noticed #23 and this issue so I figured I'd just submit fixes for all of them.

**Comment by daviddarnes** [comment]
Thanks for your efforts! I'm going to merge this in and get a new minor build of gem up

**Comment by daviddarnes** [comment]
PS. If you fancy contributing to my other theme then feel free 😅 https://github.com/daviddarnes/alembic

**Pull request merged**
